### ISSUE TITLE
editing track textures in track select menu keeps original colors

### ISSUE THREAD

**Issue by TheAkiChan** [CTR-tools/CTR-tools#207]
i am using current source code and when i edit track pictures that appear in level select menu iand Pack to VRAM in the game they are my new image but use the old image color palette. so if i edit cortex castle image it will still only be brown and red etc. or polar pass only blue and white etc.

**Comment by DCxDemo** [comment]
current code was written mostly with 4bit textures in mind, which is the vast majority of level textures. other modes are not properly supported by the importer code yet.

the textures in question are 8 bit. there is probably no bit depth check, guess you can slip 4 bit textures in, but since it only has 16 colors and the original layout remains unpatched, the game still reads the remaining 240 original colors. i think it also should've corrupt the image, cause you only overwrite half of the image data this way.

all texture\vram related stuff is located in ```CTRFramework/Code/vrm``` folder, there are these files:
* Tim.cs - to handle psx tim format (which is a bit messy and leaning towards paletted images too)
* CtrVrm.cs - to handle game's vrm files (essentially a list of tim files)
* TextureLayout.cs - to handle in-game texture description data (custom tim header basically)
* TextureReplacer.cs - actually does the replacement job

**Comment by TheAkiChan** [comment]
ah so these are meant to be 8bit textures. ok thank you.

**Comment by DCxDemo** [comment]
yeah, there is actually #135 opened for this feature, so i'm closing this
