### ISSUE TITLE
[model-reader] custom models bugs when crash

### ISSUE THREAD

**Issue by nonunknown** [CTR-tools/CTR-tools#55]
**Issue description**

When crash on walls the model gets stucked in "crash on wall animation"

![image](https://user-images.githubusercontent.com/58845030/109022133-4b948d80-769a-11eb-99d1-38f54770e895.png)

**Questions**
in some day, it will be possible to bypass 255 poly limit?

**Comment by DCxDemo** [comment]
this isn't particularly a tool bug. it happens because character model must contain 4 anims: turn, reverse, bump, jump. the game gets confused if it has no bump anim and just freezes the model in the last frame before bump occured until another event reset char state (some hazard, or uka mask).

255 limit is hardcoded, you can't go beyond that on vanilla game.

**Comment by nonunknown** [comment]
ok thanks for the answer 🗡️
